---
- name: "{{ vm.name }} | Download and extract disk image"
  ansible.builtin.include_tasks:
    file: extract.yml
  vars:
    _image_url: "{{ vm.disk_image.url }}"
    _image_dest: "{{ vm.disk_image.dest }}"
    _image_checksum: "{{ vm.disk_image.checksum | default(omit) }}"
    _image_extract: >-
      {{
        (vm.disk_image.extract | default(
          vm.disk_image.url | regex_search('\.(xz|gz|bz2|zip|tar(\.(xz|gz|bz2))?)$')
          is not none
        )) | bool
      }}

- name: "{{ vm.name }} | Get current disk image virtual size"
  become: true
  ansible.builtin.command:
    argv:
      - qemu-img
      - info
      - --force-share
      - --output=json
      - "{{ vm.disk_image.dest }}"
  register: _disk_image_info
  changed_when: false
  when: vm.disk_gb is defined

- name: "{{ vm.name }} | Resize disk image if target size is larger than current"
  become: true
  ansible.builtin.command:
    argv:
      - qemu-img
      - resize
      - "{{ vm.disk_image.dest }}"
      - "{{ vm.disk_gb }}G"
  when:
    - vm.disk_gb is defined
    - _disk_image_info is defined
    - (_disk_image_info.stdout | from_json)['virtual-size'] < (vm.disk_gb | int * 1024 * 1024 * 1024)
  changed_when: true
