---
- name: "{{ vm.name }} | Check if base qcow2 disk already exists"
  ansible.builtin.stat:
    path: "{{ libvirt_vmstore_root }}/{{ vm.name }}/{{ vm.name }}.qcow2"
  register: _qcow2_disk_stat

- name: "{{ vm.name }} | Download and extract ISO image"
  ansible.builtin.include_tasks:
    file: extract.yml
  vars:
    _image_url: "{{ vm.iso_image.url }}"
    _image_dest: "{{ vm.iso_image.dest }}"
    _image_checksum: "{{ vm.iso_image.checksum | default(omit) }}"
    _image_extract: >-
      {{
        (vm.iso_image.extract | default(
          vm.iso_image.url | regex_search('\.(xz|gz|bz2|zip|tar(\.(xz|gz|bz2))?)$')
          is not none
        )) | bool
      }}
  when: (vm.iso_image.enable_mount | default(true)) | bool


- name: "{{ vm.name }} | Create base qcow2 disk for ISO-based VM"
  become: true
  ansible.builtin.command:
    argv:
      - qemu-img
      - create
      - -f
      - qcow2
      - "{{ libvirt_vmstore_root }}/{{ vm.name }}/{{ vm.name }}.qcow2"
      - "{{ vm.disk_gb | default(20) }}G"
  when: not _qcow2_disk_stat.stat.exists
  changed_when: true

- name: "{{ vm.name }} | Resize disk image if needed"
  ansible.builtin.include_tasks:
    file: resize-qcow2-disk.yml
  vars:
    _qcow2_disk_path: "{{ libvirt_vmstore_root }}/{{ vm.name }}/{{ vm.name }}.qcow2"
