services:
  actual-budget:
    container_name: actual-budget
    image: docker.io/actualbudget/actual-server:26.2.0@sha256:c34346f87725b9cce5dca5af1a2a9b989127d592cc4c6af5cf4652d4a86def90
    environment:
      ACTUAL_OPENID_DISCOVERY_URL: "https://auth.{{ main_domain }}/.well-known/openid-configuration"
      ACTUAL_OPENID_CLIENT_ID: "{{ backbone__authelia__oidc_actual_budget_clientid }}"
      ACTUAL_OPENID_CLIENT_SECRET: "{{ backbone__authelia__oidc_actual_budget_clientsecret }}"
      ACTUAL_OPENID_SERVER_HOSTNAME: "https://actual.{{ main_domain }}"
      ACTUAL_OPENID_ENFORCE: "true"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.actual.entryPoints=websecure
      - traefik.http.routers.actual.rule=Host(`actual.{{ main_domain }}`)
      - traefik.http.routers.actual.service=actual
      - traefik.http.services.actual.loadBalancer.server.port=5006
    volumes:
      - "{{ docker_mounts_directory }}/actual-budget:/data"
    restart: unless-stopped
networks:
  web:
    external: true
