# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys: &all_keys
  - &snyssen_gaming age1s4xdzf2qqvcu60ej7tk2r9pc6zl6kmxl2lg30dpqfq5ms47ek97q3dgpse
  - &snyssen_sninful age1n9kh0lcwpcth7ex4n9lc2h5enl45pmmy2wqzhznwulgq9r9elf4qp3vr2k
  - &snyssen_purplehaze age1299cj79spmwd93hjz80v5s743a0vr6cjjkm8wggmc4z0x54e69fs9a0hqs
  - &snyssen_blackfog age104pa77q73yt8hht4kv05gpk7hyayefy697lfe63dl0ua6dsej54s3mmrgj
  - &root_ingress age17gnf6sp839a0wlhd998vn0wv5rrcwle34pky8mfn5d8dymm99vtsm9xygx
  - &root_hypervisor age1ch6ewtc2v3v6u4jjznq860m3vkyvz0l3z889sjmfxpykm27xaf4q6e9p9n
  - &root_scrypted age1zxzqqaa29ekzf8s27a46xp2gn2hqsstdvp959lq8cjlw9njv5scssywq88
  - &root_technitium_primary age1flln5jgw557ft9zff073ccer3hjcv344zaypm7gvrx9zlcnzsgws6ssrxg
  - &root_technitium_secondary age1wflhsef62cr7syf3cza5jkj4ylhrqj93yzpn862xxscp9g838caq09uzy8
  - &root_apps age1un9lm7u4whghrydmeyxhv9mmkt7tyhjejn0mhesfc6g3x60atflqna7lg7
creation_rules:
  # global secrets
  - path_regex: nix/data/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age: *all_keys
  # host specific secrets
  - path_regex: nix/hosts/purplehaze/data/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age:
          - *snyssen_purplehaze
          - *snyssen_gaming
          - *snyssen_blackfog
  - path_regex: nix/hosts/gaming/data/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age:
          - *snyssen_gaming
          - *snyssen_purplehaze
          - *snyssen_blackfog
  - path_regex: nix/hosts/sninful/data/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age:
          - *snyssen_sninful
          - *snyssen_purplehaze
  - path_regex: nix/hosts/blackfog/data/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age:
          - *snyssen_purplehaze
          - *snyssen_blackfog
  - path_regex: nix/hosts/ingress/data/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age:
          - *root_ingress
          - *snyssen_gaming
          - *snyssen_purplehaze
          - *snyssen_blackfog
  - path_regex: nix/hosts/hypervisor/data/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age:
          - *root_hypervisor
          - *snyssen_gaming
          - *snyssen_purplehaze
          - *snyssen_blackfog
  - path_regex: nix/hosts/scrypted/data/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age:
          - *root_scrypted
          - *snyssen_purplehaze
          - *snyssen_blackfog
  - path_regex: nix/hosts/technitium-primary/data/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age:
          - *root_technitium_primary
          - *snyssen_purplehaze
          - *snyssen_blackfog
  - path_regex: nix/hosts/technitium-secondary/data/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age:
          - *root_technitium_secondary
          - *snyssen_purplehaze
          - *snyssen_blackfog
  - path_regex: nix/hosts/apps/data/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age:
          - *root_apps
          - *snyssen_purplehaze
          - *snyssen_blackfog
