site_name: Mother of All Infra Documentation
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)"
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"
