{
  inputs,
  flake,
  config,
  ...
}:
{

  #
  ## WORKAROUNDS
  #

  # should be set by blueprint, except it's not: https://github.com/numtide/blueprint/issues/115
  nixpkgs.config.allowUnfree = true;
  nixpkgs.overlays = [
    inputs.nix-vscode-extensions.overlays.default
    (final: _: {
      unstable = import inputs.nixpkgs-unstable {
        inherit (final.stdenv.hostPlatform) system;
        inherit (final) config;
      };
    })
  ];

  #########################

  imports = [
    flake.modules.nixos.disko
    # NOTE: generated by 'nixos-generate-config' on first boot; replace with actual output.
    ./hardware-configuration.nix

    flake.modules.nixos.sops
    flake.modules.nixos.cache
    flake.modules.nixos.grub
    flake.modules.nixos.kbd-layout
    flake.modules.nixos.shell
    flake.modules.nixos.locale
    flake.modules.nixos.nh

    flake.modules.nixos.tailscale
    flake.modules.nixos.nfs-mounts
    flake.modules.nixos.docker
    flake.modules.nixos.docker-networks
    flake.modules.nixos.compose-stacks

    flake.modules.nixos.crowdsec-firewall-bouncer
    flake.modules.nixos.prometheus-node-exporter
    flake.modules.nixos.grafana-alloy
  ];

  # ---------------------------------------------------------------------------
  # Disk layout
  # ---------------------------------------------------------------------------

  disko.layout = "single-btrfs-luks-virtiofs-key";

  # ---------------------------------------------------------------------------
  # Secrets (SOPS)
  # ---------------------------------------------------------------------------
  # NOTE: nix/hosts/apps/data/secrets.yaml is currently a plaintext placeholder.
  # Replace it with a SOPS-encrypted file before running 'nixos-rebuild switch'.
  # See the file header comment and docs/hypervisor/apps-migration-plan.md for
  # the bootstrap procedure.  'nix build' will succeed, but activation will fail
  # until real encrypted secrets are in place.

  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
  sops.secrets = {
    "tailscale/authKey" = {
      sopsFile = ./data/secrets.yaml;
    };
    "crowdsec-firewall-bouncer/api_key" = {
      sopsFile = ./data/secrets.yaml;
    };
    "users/snyssen/passwordHash" = {
      sopsFile = ./data/secrets.yaml;
      neededForUsers = true;
    };
  };

  # ---------------------------------------------------------------------------
  # Networking
  # ---------------------------------------------------------------------------

  networking = {
    useNetworkd = true;
    firewall = {
      enable = true;
      allowedTCPPorts = [
        # Prometheus node exporter
        9100
      ];
    };
  };

  # ---------------------------------------------------------------------------
  # Tailscale VPN
  # ---------------------------------------------------------------------------

  tailscale.autoconnect = {
    enable = true;
    authKeyPath = config.sops.secrets."tailscale/authKey".path;
    enableSSH = true;
    tags = [ "server" ];
  };

  # ---------------------------------------------------------------------------
  # Storage
  # ---------------------------------------------------------------------------

  # Local app-data tier: lives on the VM OS disk (backed by vmstore SSD RAID-1).
  # Replaces /home/snyssen/data on the old Ubuntu host.
  systemd.tmpfiles.rules = [
    "d /var/lib/app-data 0755 root root -"
  ];

  # Bulk storage tier: NFS mount backed by hypervisor /mnt/bulk/apps.
  # Replaces /mnt/storage on the old Ubuntu host.
  nfsMounts.enable = true;
  nfsMounts.mounts.bulk = {
    path = "/mnt/bulk";
    host = "hypervisor";
    remotePath = "/mnt/bulk/apps";
    dependsOn.tailscale = true;
  };

  # ---------------------------------------------------------------------------
  # Security
  # ---------------------------------------------------------------------------

  crowdsec-firewall-bouncer.apiKeyPath = config.sops.secrets."crowdsec-firewall-bouncer/api_key".path;

  # ---------------------------------------------------------------------------
  # Monitoring
  # ---------------------------------------------------------------------------

  prometheus-node-exporter = {
    openFirewall = true;
  };

  grafana-alloy = {
    varlogs.enable = true;
    journald.enable = true;
    containerlogs.enable = true;
  };

  # ---------------------------------------------------------------------------
  # Docker & networks
  # ---------------------------------------------------------------------------

  # Pre-create shared Docker bridge networks before any compose stack starts.
  # The legacy 'lan' ipvlan network is intentionally NOT created here.
  docker-networks.networks = [
    "web"
    "db"
    "ldap"
    "monitoring"
  ];

  # ---------------------------------------------------------------------------
  # Compose stacks
  # ---------------------------------------------------------------------------

  # Stacks are added here incrementally as they are migrated from Ansible.
  # Each stack's compose file lives at:
  #   nix/hosts/apps/compose/<stack_name>/docker-compose.yaml
  #
  # Example entry (uncomment and adapt when migrating a stack):
  #
  # compose-stacks.stacks.databases = {
  #   composeFile    = ./compose/databases/docker-compose.yaml;
  #   environmentFile = config.sops.secrets."stacks/databases/env".path;
  #   extraAfter     = [
  #     "docker-network-db.service"
  #   ];
  # };
  #
  # Stacks that need the bulk NFS share must also add:
  #   extraAfter = [ "mnt-bulk.automount" ];

  # ---------------------------------------------------------------------------
  # SSH
  # ---------------------------------------------------------------------------

  services.openssh = {
    enable = true;
    openFirewall = true;
    settings.PasswordAuthentication = false;
    settings.PermitRootLogin = "no";
  };

  # ---------------------------------------------------------------------------
  # Shell
  # ---------------------------------------------------------------------------

  shell.default = "fish";

  # ---------------------------------------------------------------------------
  # Users
  # ---------------------------------------------------------------------------

  users = {
    mutableUsers = false;
    users.snyssen = {
      isNormalUser = true;
      extraGroups = [
        "networkmanager"
        "wheel"
      ];
      hashedPasswordFile = config.sops.secrets."users/snyssen/passwordHash".path;
      openssh.authorizedKeys.keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG68A6FS8yzwzaOUsoKHL9bc+2gB1P5OQriFjEWzG/LH snyssen@blackfog"
      ];
    };
  };

  # ---------------------------------------------------------------------------
  # Nix settings
  # ---------------------------------------------------------------------------

  # TODO: make this part automatically defined
  nix.settings = {
    experimental-features = [
      "nix-command"
      "flakes"
    ];
    auto-optimise-store = true;
  };

  system.name = "apps";
  networking.hostName = "apps";
  system.stateVersion = "25.11";
}
