services:
  personal-website:
    image: ghcr.io/snyssen/personal-website:2.12.1@sha256:c0216efb084e53be861d0ed9644f15119405d56a2ee84f34d4519c14d2e040b0
    restart: unless-stopped
    container_name: personal-website
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.personal-website.entryPoints=websecure
      - traefik.http.routers.personal-website.rule=Host(`{{ main_domain }}`)
      - traefik.http.routers.personal-website.middlewares=traefik-compress
      - traefik.http.routers.personal-website.service=personal-website
      - traefik.http.services.personal-website.loadBalancer.server.port=80
    mem_limit: 512m

networks:
  web:
    external: true
