services:
  personal-website:
    image: ghcr.io/snyssen/personal-website:2.12.4@sha256:d69d3d2094fcdf94adeba0e60bdeebca6e9cbbd1392ce9dd7fdff19aa908213e
    restart: unless-stopped
    container_name: personal-website
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.personal-website.entryPoints=websecure
      - traefik.http.routers.personal-website.rule=Host(`{{ main_domain }}`)
      - traefik.http.routers.personal-website.middlewares=traefik-compress
      - traefik.http.routers.personal-website.service=personal-website
      - traefik.http.services.personal-website.loadBalancer.server.port=80
    mem_limit: 512m

networks:
  web:
    external: true
