services:
  personal-website:
    image: ghcr.io/snyssen/personal-website:2.12.5@sha256:bcf74c03e5e724ac29aba0c788691dbc05133411083b68d6841c3f1743562c87
    restart: unless-stopped
    container_name: personal-website
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.personal-website.entryPoints=websecure
      - traefik.http.routers.personal-website.rule=Host(`{{ main_domain }}`)
      - traefik.http.routers.personal-website.middlewares=traefik-compress
      - traefik.http.routers.personal-website.service=personal-website
      - traefik.http.services.personal-website.loadBalancer.server.port=80
    mem_limit: 512m

networks:
  web:
    external: true
