services:

  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:v1.150.0@sha256:cba0969087ca70a3ec72ebcd1491a6c8391a7da2c0b92738231dd9c7ad55df4d
    restart: unless-stopped
    environment:
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    volumes:
      - /mnt/storage/matrix/synapse:/data
    networks:
      - web
      - db
      - bridges
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.synapse.entryPoints=websecure
      - traefik.http.routers.synapse.rule=Host(`matrix.{{ main_domain }}`)
      - traefik.http.routers.synapse.service=synapse
      - traefik.http.services.synapse.loadBalancer.server.port=8008

  matrix_mas:
    container_name: matrix_mas
    image: ghcr.io/element-hq/matrix-authentication-service:1.14.0@sha256:35721fc3181887568cb051f0a6ccb05cacb5b8b56cfbc1214db05df7f288e5f4
    restart: unless-stopped
    environment:
      MAS_CONFIG: /config/mas_config.yaml
    volumes:
      - /mnt/storage/matrix/mas:/config
    networks:
      - web
      - db
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.matrix_mas.entryPoints=websecure
      # Regex path added as compatibility layer as per https://element-hq.github.io/matrix-authentication-service/setup/reverse-proxy.html#compatibility-layer
      - traefik.http.routers.matrix_mas.rule=Host(`matrix-mas.{{ main_domain }}`) || (Host(`matrix.{{ main_domain }}`) && PathRegexp(`^/_matrix/client/(.*)/(login|logout|refresh)`))
      - traefik.http.routers.matrix_mas.service=matrix_mas
      - traefik.http.services.matrix_mas.loadBalancer.server.port=8080



  element:
    container_name: element
    image: vectorim/element-web:v1.12.13@sha256:5107e63026c13ed014f743e485821b7d4b56d275a41e76303859bb14f5f94eb6
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/element/config.json:/app/config.json:ro
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.element.entryPoints=websecure
      - traefik.http.routers.element.rule=Host(`element.{{ main_domain }}`)
      - traefik.http.routers.element.service=element
      - traefik.http.services.element.loadBalancer.server.port=80

  ###########
  # Bridges #
  ###########
  matrix-discord:
    container_name: matrix-discord
    image: dock.mau.dev/mautrix/discord:v0.7.6@sha256:965b25cb81e7c8133d2adda9057f9fd4c25bd645f1649d8d91129edfeb79d53d
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_discord:/data
    networks:
      - bridges
      - db

  matrix-signal:
    container_name: matrix-signal
    image: dock.mau.dev/mautrix/signal:v26.03@sha256:0e3be8a024395a0e9a28b3d01621bbca302fc4f1cadfd5ae9e3610d41ac2bdc2
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_signal:/data
    networks:
      - bridges
      - db

  matrix-whatsapp:
    container_name: matrix-whatsapp
    image: dock.mau.dev/mautrix/whatsapp:v26.03@sha256:b49009312361d9ea0d7090716fd09f2323f477b32bd119648c6ca2d558a3e236
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_whatsapp:/data
    networks:
      - bridges
      - db

  matrix-meta:
    container_name: matrix-meta
    image: dock.mau.dev/mautrix/meta:v26.02@sha256:3a1e55b0eb86d9841f9382e1b3dd33d768ffcfa9b7d65cdbf672c385f9903ade
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_meta:/data
    networks:
      - bridges
      - db

  ###########
  #  Bots   #
  ###########
  maubot:
    container_name: maubot
    image: dock.mau.dev/maubot/maubot:v0.6.0@sha256:6968ddea1e08aa7f8ac70ac7a706663fe8d7b4d6f96cd7a6bb8548637fb8cd17
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/maubot:/data
      - "{{ docker_mounts_directory }}/matrix/maubot/dbs:/data/dbs"
    networks:
      - bridges
      - db
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.maubot.entryPoints=websecure
      - traefik.http.routers.maubot.rule=Host(`maubot.{{ main_domain }}`)
      - traefik.http.routers.maubot.service=maubot
      - traefik.http.services.maubot.loadBalancer.server.port=29316
      - traefik.http.routers.maubot.middlewares=lan-whitelist

networks:
  web:
    external: true
  db:
    external: true
  bridges:
