services:

  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:v1.146.0@sha256:5e629e8cae72b36c464e49210568932c2a31a2cc8ff3ed861edcd505f1398f95
    restart: unless-stopped
    environment:
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    volumes:
      - /mnt/storage/matrix/synapse:/data
    networks:
      - web
      - db
      - bridges
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.synapse.entryPoints=websecure
      - traefik.http.routers.synapse.rule=Host(`matrix.{{ main_domain }}`)
      - traefik.http.routers.synapse.service=synapse
      - traefik.http.services.synapse.loadBalancer.server.port=8008

  matrix_mas:
    container_name: matrix_mas
    image: ghcr.io/element-hq/matrix-authentication-service:1.10.0@sha256:83aa6b02f6599584de9b80d07057bc5c054f4704351287170711666e6056649f
    restart: unless-stopped
    environment:
      MAS_CONFIG: /config/mas_config.yaml
    volumes:
      - /mnt/storage/matrix/mas:/config
    networks:
      - web
      - db
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.matrix_mas.entryPoints=websecure
      # Regex path added as compatibility layer as per https://element-hq.github.io/matrix-authentication-service/setup/reverse-proxy.html#compatibility-layer
      - traefik.http.routers.matrix_mas.rule=Host(`matrix-mas.{{ main_domain }}`) || (Host(`matrix.{{ main_domain }}`) && PathRegexp(`^/_matrix/client/(.*)/(login|logout|refresh)`))
      - traefik.http.routers.matrix_mas.service=matrix_mas
      - traefik.http.services.matrix_mas.loadBalancer.server.port=8080



  element:
    container_name: element
    image: vectorim/element-web:v1.12.9@sha256:ed7a0b4a358f65715f51a7a637f5b309c3c1d8e4c170e17cc06c7bb1b964fac3
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/element/config.json:/app/config.json:ro
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.element.entryPoints=websecure
      - traefik.http.routers.element.rule=Host(`element.{{ main_domain }}`)
      - traefik.http.routers.element.service=element
      - traefik.http.services.element.loadBalancer.server.port=80

  ###########
  # Bridges #
  ###########
  matrix-discord:
    container_name: matrix-discord
    image: dock.mau.dev/mautrix/discord:v0.7.5@sha256:c447c097124d47824bc446f859ba1aa6ab8fda4b4d0477d1ca28db4a4cbb059b
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_discord:/data
    networks:
      - bridges
      - db

  matrix-signal:
    container_name: matrix-signal
    image: dock.mau.dev/mautrix/signal:v26.01@sha256:7123afe68978eb6e7326d0beeb5bae73cf36fe51ec39c0a6fddab50e8a2f67d9
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_signal:/data
    networks:
      - bridges
      - db

  matrix-whatsapp:
    container_name: matrix-whatsapp
    image: dock.mau.dev/mautrix/whatsapp:v26.01@sha256:cbd395cc939cdfab127a9bac1d090a12cb10a3f24046c3324c1ba4bc5f6c4b72
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_whatsapp:/data
    networks:
      - bridges
      - db

  matrix-meta:
    container_name: matrix-meta
    image: dock.mau.dev/mautrix/meta:v25.12@sha256:1ba769047d4910675eed1ceb820c5cb6e8f6d0633ef4ce005ab802128c3b904f
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_meta:/data
    networks:
      - bridges
      - db

  ###########
  #  Bots   #
  ###########
  maubot:
    container_name: maubot
    image: dock.mau.dev/maubot/maubot:v0.6.0@sha256:6968ddea1e08aa7f8ac70ac7a706663fe8d7b4d6f96cd7a6bb8548637fb8cd17
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/maubot:/data
      - "{{ docker_mounts_directory }}/matrix/maubot/dbs:/data/dbs"
    networks:
      - bridges
      - db
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.maubot.entryPoints=websecure
      - traefik.http.routers.maubot.rule=Host(`maubot.{{ main_domain }}`)
      - traefik.http.routers.maubot.service=maubot
      - traefik.http.services.maubot.loadBalancer.server.port=29316
      - traefik.http.routers.maubot.middlewares=lan-whitelist

networks:
  web:
    external: true
  db:
    external: true
  bridges:
