services:

  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:v1.152.1@sha256:ea13612748d2c3cd7d37314e4d2bb3833831e7fe9c1cc2ba2a05a0e51ab78297
    restart: unless-stopped
    environment:
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    volumes:
      - /mnt/storage/matrix/synapse:/data
    networks:
      - web
      - db
      - bridges
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.synapse.entryPoints=websecure
      - traefik.http.routers.synapse.rule=Host(`matrix.{{ main_domain }}`)
      - traefik.http.routers.synapse.service=synapse
      - traefik.http.services.synapse.loadBalancer.server.port=8008

  matrix_mas:
    container_name: matrix_mas
    image: ghcr.io/element-hq/matrix-authentication-service:1.16.0@sha256:969d33b20ef4449937ee7bce9e05d159c10d9d1504d9374f2b7d43087bbff924
    restart: unless-stopped
    environment:
      MAS_CONFIG: /config/mas_config.yaml
    volumes:
      - /mnt/storage/matrix/mas:/config
    networks:
      - web
      - db
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.matrix_mas.entryPoints=websecure
      # Regex path added as compatibility layer as per https://element-hq.github.io/matrix-authentication-service/setup/reverse-proxy.html#compatibility-layer
      - traefik.http.routers.matrix_mas.rule=Host(`matrix-mas.{{ main_domain }}`) || (Host(`matrix.{{ main_domain }}`) && PathRegexp(`^/_matrix/client/(.*)/(login|logout|refresh)`))
      - traefik.http.routers.matrix_mas.service=matrix_mas
      - traefik.http.services.matrix_mas.loadBalancer.server.port=8080



  element:
    container_name: element
    image: vectorim/element-web:v1.12.17@sha256:f4a81a24d49a9c5b97e02e77a3013ec799873e500e69041078a28be98e4f1280
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/element/config.json:/app/config.json:ro
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.element.entryPoints=websecure
      - traefik.http.routers.element.rule=Host(`element.{{ main_domain }}`)
      - traefik.http.routers.element.service=element
      - traefik.http.services.element.loadBalancer.server.port=80

  ###########
  # Bridges #
  ###########
  matrix-discord:
    container_name: matrix-discord
    image: dock.mau.dev/mautrix/discord:v0.7.6@sha256:e4946b0df6a2786c88ed490e0d2692e352f1b79b9ff0e821a33764bd8bd1fffd
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_discord:/data
    networks:
      - bridges
      - db

  matrix-signal:
    container_name: matrix-signal
    image: dock.mau.dev/mautrix/signal:v26.04@sha256:aa3891001893be88ef6f7c692d254a1ed11dbcaf29d3c02e8ed4ddf9df259244
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_signal:/data
    networks:
      - bridges
      - db

  matrix-whatsapp:
    container_name: matrix-whatsapp
    image: dock.mau.dev/mautrix/whatsapp:v26.04@sha256:9f28c04c746af9fe8e93163489dae0f4191626e2ca02a9302df62afbeefc9eba
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_whatsapp:/data
    networks:
      - bridges
      - db

  matrix-meta:
    container_name: matrix-meta
    image: dock.mau.dev/mautrix/meta:v26.04@sha256:080d23a07d08a1055cfa659266bbfc3bf754a8304b95df5c1c6b51de97b79d66
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/matrix_meta:/data
    networks:
      - bridges
      - db

  ###########
  #  Bots   #
  ###########
  maubot:
    container_name: maubot
    image: dock.mau.dev/maubot/maubot:v0.6.0@sha256:6968ddea1e08aa7f8ac70ac7a706663fe8d7b4d6f96cd7a6bb8548637fb8cd17
    restart: unless-stopped
    volumes:
      - /mnt/storage/matrix/maubot:/data
      - "{{ docker_mounts_directory }}/matrix/maubot/dbs:/data/dbs"
    networks:
      - bridges
      - db
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.maubot.entryPoints=websecure
      - traefik.http.routers.maubot.rule=Host(`maubot.{{ main_domain }}`)
      - traefik.http.routers.maubot.service=maubot
      - traefik.http.services.maubot.loadBalancer.server.port=29316
      - traefik.http.routers.maubot.middlewares=lan-whitelist

networks:
  web:
    external: true
  db:
    external: true
  bridges:
