services:
  alloy:
    image: grafana/alloy:v1.12.1@sha256:c311595156fca7b1131683d383dae1acfd29e8879d347161d2a6f714ebac0c0b
    container_name: alloy
    restart: unless-stopped
    volumes:
      - "{{ docker_mounts_directory }}/monitoring/alloy/alloy-config.alloy:/etc/alloy/config.alloy"
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --disable-reporting /etc/alloy/config.alloy
    ports:
      - 12345:12345
    mem_limit: 2g
