services:
  alloy:
    image: grafana/alloy:v1.14.0@sha256:f50931848bd8178774521767bb46b905e1a081301950ff28d7623c9db7c01076
    container_name: alloy
    restart: unless-stopped
    volumes:
      - "{{ docker_mounts_directory }}/monitoring/alloy/alloy-config.alloy:/etc/alloy/config.alloy"
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --disable-reporting /etc/alloy/config.alloy
    ports:
      - 12345:12345
    mem_limit: 2g
