services:
  alloy:
    image: grafana/alloy:v1.15.1@sha256:1f40cf52adda8fab3e058f9347a5d165624ecb9fbc1527769cb744748961940d
    container_name: alloy
    restart: unless-stopped
    volumes:
      - "{{ docker_mounts_directory }}/monitoring/alloy/alloy-config.alloy:/etc/alloy/config.alloy"
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --disable-reporting /etc/alloy/config.alloy
    ports:
      - 12345:12345
    mem_limit: 2g
