- hosts: apps
  gather_facts: false
  tasks:
    - name: Parse expected autorestic arguments
      ansible.builtin.set_fact:
        backup_locations_args: "-l {{ backup_locations | join(' -l ') }}"
      when:
        - backup_locations is defined
        - backup_locations | length > 0
    - name: run autorestic forget
      become: true
      ansible.builtin.shell: >-
        /root/scripts/autorestic_log_wrapper.sh autorestic --ci forget
        {{ backup_locations_args if backup_locations_args is defined else '-a' }}
        {{ '--dry-run' if (backup_dry_run | default(false)) }}
        {{ '--prune' if (backup_prune | default(true)) }}
      register: returned_value
    - name: Showing stdoud
      ansible.builtin.debug:
        var: returned_value.stdout_lines
