services:
  skyrim_together:
    image: tiltedphoques/st-reborn-server:1.8.1@sha256:2d81cab0ccbd958ef920c81aa239a858b57288f230ae19908c77ee765d68cf84
    container_name: skyrim_together
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - traefik.udp.routers.skyrim_together.entryPoints=skyrim_together
      - traefik.udp.routers.skyrim_together.service=skyrim_together
      - traefik.udp.services.skyrim_together.loadBalancer.server.port=10578
    volumes:
      - /mnt/storage/skyrim_together/config:/st-server/config
      - /mnt/storage/skyrim_together/logs:/st-server/logs
      - /mnt/storage/skyrim_together/Data:/st-server/Data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  web:
    external: true
