# TODO: actually, that could probably live on the host -> https://wiki.nixos.org/wiki/PostgreSQL
services:
  postgres:
    image: postgres:18.6@sha256:06cad38a5d9f5d24b4d83d86def30795d5e4b757fedbf5281172b576dedcd941
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - "/var/lib/app-data/databases/postgres/data:/var/lib/postgresql"
    # Expose port directly on host so ansible can connect to manage databases
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4:9.17@sha256:2f4ce946ddf8360680d7eff4eaba1d91859eb6b4003e6623bad5c63a322c2f4d
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@snyssen.be"
      PGADMIN_DEFAULT_PASSWORD: "thisisatest"
    networks:
      - db
    ports:
      - 8888:80

networks:
  db:
    external: true
