services:
  team_wiki:
    image: ghcr.io/requarks/wiki:2@sha256:e013da5e3b634fb6e09f469f2d63fe3a138d79087455bf1e9d804c7bd5109a09
    container_name: team_wiki
    networks:
      - web
      - db
      - ldap
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: team_wiki
      DB_USER: team_wiki
      DB_PASS: "{{ team_wiki__db_pass }}"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.team_wiki.entryPoints=websecure
      - traefik.http.routers.team_wiki.rule=Host(`{{ team_domain }}`)
      - traefik.http.routers.team_wiki.service=team_wiki
      - traefik.http.services.team_wiki.loadBalancer.server.port=3000

networks:
  web:
    external: true
  db:
    external: true
  ldap:
    external: true
