services:
  team_wiki:
    image: ghcr.io/requarks/wiki:2@sha256:68f0d1848261ae76492ba358e30a96a76fed5d97a3fff381656082bf90f70d7e
    container_name: team_wiki
    networks:
      - web
      - db
      - ldap
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: team_wiki
      DB_USER: team_wiki
      DB_PASS: "{{ team_wiki__db_pass }}"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.team_wiki.entryPoints=websecure
      - traefik.http.routers.team_wiki.rule=Host(`{{ team_domain }}`)
      - traefik.http.routers.team_wiki.tls.certresolver={{ (backbone__acme_domains | selectattr("main", "equalto", team_domain) | map(attribute="resolver") | first) }}
      - traefik.http.routers.team_wiki.service=team_wiki
      - traefik.http.services.team_wiki.loadBalancer.server.port=3000

networks:
  web:
    external: true
  db:
    external: true
  ldap:
    external: true
