services:
{% for vault in quartz__vaults %}
  quartz-{{ vault.name }}:
    image: ghcr.io/jackyzha0/quartz:latest@sha256:e2cb8067171f6e50a39a32c2214ab17f0938a0e4ea8b3d6b9248a0b4bd658a65
    container_name: quartz-{{ vault.name }}
    restart: unless-stopped
    volumes:
      - "{{ vault.path }}:/usr/src/app/content:ro"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.quartz-{{ vault.name }}.entryPoints=websecure
      - traefik.http.routers.quartz-{{ vault.name }}.rule=Host(`{{ vault.name }}.notes.{{ main_domain }}`)
      - traefik.http.routers.quartz-{{ vault.name }}.middlewares=authelia@docker,traefik-compress
      - traefik.http.routers.quartz-{{ vault.name }}.service=quartz-{{ vault.name }}
      - traefik.http.services.quartz-{{ vault.name }}.loadBalancer.server.port=8080
{% endfor %}

networks:
  web:
    external: true
