- name: Create folders
  become: true
  ansible.builtin.file:
    path: "{{ item.src }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
    - src: "{{ docker_mounts_directory }}/crowdsec/crowdsec"
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
    - src: "{{ docker_mounts_directory }}/crowdsec/data"
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
    - src: "{{ docker_mounts_directory }}/crowdsec-web-ui/data"
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"

- name: Deploy config files
  become: true
  ansible.builtin.template:
    src: "crowdsec/{{ item }}"
    dest: "{{ docker_mounts_directory }}/crowdsec/crowdsec/{{ item }}"
    mode: "600"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
  loop:
    - config.yaml.local
    - acquis.d/ssh.yaml
    - acquis.d/ssh-journald.yaml
    - acquis.d/authelia.yaml
    - acquis.d/traefik.yaml
    - acquis.d/traefik-varlogs.yaml
    - parsers/s02-enrich/00-whitelist-attic.yaml

- ansible.builtin.include_role:
    name: snyssen.compose_deploy
  vars:
    stack_name: crowdsec

- name: Create monitors
  lucasheld.uptime_kuma.monitor:
    name: "{{ item.name }}"
    type: http
    url: "{{ item.url }}"
  loop:
    - name: crowdsec
      url: "http://crowdsec:6060/metrics"
