services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.7@sha256:6ca53ad26196ca59ddd4fa692a586b73d8fcde085046163b9ca2f04887dca563
    container_name: crowdsec
    restart: unless-stopped
    networks:
      - monitoring
      - web
    volumes:
      - "{{ docker_mounts_directory }}/crowdsec/crowdsec:/etc/crowdsec"
      - "{{ docker_mounts_directory }}/crowdsec/data:/var/lib/crowdsec/data"
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.crowdsec.entryPoints=websecure
      - traefik.http.routers.crowdsec.rule=Host(`crowdsec.{{ main_domain }}`)
      - traefik.http.routers.crowdsec.middlewares=lan-whitelist
      - traefik.http.routers.crowdsec.service=crowdsec
      - traefik.http.services.crowdsec.loadBalancer.server.port=8080
    environment:
      BOUNCER_KEY_firewall: "{{ crowdsec__firewall_bouncer__api_key }}"
      COLLECTIONS: "LePresidente/authelia crowdsecurity/traefik"

  crowdsec-web-ui:
    image: ghcr.io/theduffman85/crowdsec-web-ui:latest@sha256:a2e8ee4299c55f3fa276602071f7ea6d1be333de209450615af42ba2b1932fc7
    container_name: crowdsec-web-ui
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.crowdsec-web-ui.entryPoints=websecure
      - traefik.http.routers.crowdsec-web-ui.rule=Host(`dash.crowdsec.{{ main_domain }}`)
      - traefik.http.routers.crowdsec-web-ui.middlewares=authelia@docker
      - traefik.http.routers.crowdsec-web-ui.service=crowdsec-web-ui
      - traefik.http.services.crowdsec-web-ui.loadBalancer.server.port=3000
    environment:
      - CROWDSEC_URL=http://crowdsec:8080
      - CROWDSEC_USER={{ crowdsec__webui_user }}
      - CROWDSEC_PASSWORD={{ crowdsec__webui_password }}
      # Optional: Lookback period for alerts/stats (default: 168h/7d)
      - CROWDSEC_LOOKBACK_PERIOD=5d
      # Optional: Backend auto-refresh interval. Values: 0 (Off), 5s, 30s (default), 1m, 5m
      - CROWDSEC_REFRESH_INTERVAL=30s
      # Optional: Idle Mode settings to save resources
      # Interval to use when no users are active (default: 5m)
      - CROWDSEC_IDLE_REFRESH_INTERVAL=5m
      # Time without API requests to consider system idle (default: 2m)
      - CROWDSEC_IDLE_THRESHOLD=2m
      # Optional: Interval for full cache refresh (default: 5m)
      # Forces a complete data reload when active, skipped when idle.
      - CROWDSEC_FULL_REFRESH_INTERVAL=5m
    volumes:
      - "{{ docker_mounts_directory }}/crowdsec-web-ui/data:/app/data"
networks:
  monitoring:
    external: true
  web:
    external: true
