services:
  traefik:
    image: traefik:v3.7.10@sha256:9c3b91d5fb7770853ca5c1124a23c34bf2d9b47ffaebeab2614cbaf410dcb2ac
    restart: unless-stopped
    container_name: traefik
    networks:
      - web
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=100.120.249.84" # Trust Ingress tailnet IP
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver={{ backbone__acme_default_resolver }}"
      {%- set default_tls_domain_index = namespace(value=0) +%}
      {%- for acme_domain in backbone__acme_domains if acme_domain.resolver == backbone__acme_default_resolver +%}
      - "--entrypoints.websecure.http.tls.domains[{{ default_tls_domain_index.value }}].main={{ acme_domain.main }}"
      - "--entrypoints.websecure.http.tls.domains[{{ default_tls_domain_index.value }}].sans={{ acme_domain.sans | join(',') }}"
      {%- set default_tls_domain_index.value = default_tls_domain_index.value + 1 +%}
      {%- endfor +%}

      - "--entryPoints.unifi-stun.address=:3478/udp"
      - "--entryPoints.unifi-discovery.address=:10001/udp"
      - "--entryPoints.unifi-comm.address=:8081"
      # TODO: fix DLNA (should be exposed as physical device)
      # - "--entryPoints.unifi-discovery-l2.address=:1900/udp"
      - "--entryPoints.minecraft.address=:25565"
      - "--entryPoints.jellyfin-discovery.address=:7359/udp"
      # TODO: fix DLNA (should be exposed as physical device)
      # - "--entryPoints.dlna.address=:1900/udp"
      - "--entryPoints.syncthing.address=:22000"
      - "--entryPoints.syncthing-udp.address=:22000/udp"
      - "--entryPoints.syncthing-discovery.address=:21027/udp"
      - "--entryPoints.skyrim_together.address=:10578/udp"

      {%- for acme_resolver in backbone__acme_resolvers +%}
      - "--certificatesResolvers.{{ acme_resolver.name }}.acme.email={{ smtp__to }}"
      - "--certificatesResolvers.{{ acme_resolver.name }}.acme.storage={{ acme_resolver.storage }}"
      - "--certificatesresolvers.{{ acme_resolver.name }}.acme.caserver={{ acme_resolver.ca_server }}"
      - "--certificatesResolvers.{{ acme_resolver.name }}.acme.tlsChallenge=false"
      - "--certificatesresolvers.{{ acme_resolver.name }}.acme.dnschallenge=true"
      - "--certificatesresolvers.{{ acme_resolver.name }}.acme.dnschallenge.provider={{ acme_resolver.provider }}"
      - "--certificatesresolvers.{{ acme_resolver.name }}.acme.dnschallenge.resolvers={{ acme_resolver.dns_resolvers | join(',') }}"
      - "--certificatesresolvers.{{ acme_resolver.name }}.acme.dnschallenge.delaybeforecheck={{ acme_resolver.delay_before_check }}"
      - "--certificatesResolvers.{{ acme_resolver.name }}.acme.httpChallenge=false"
      - "--certificatesResolvers.{{ acme_resolver.name }}.acme.httpChallenge.entryPoint=web"
      {%- endfor +%}

      # Do not check certificates from apps (some apps, such as unifi, do not provide a way to disable their own cert...)
      - "--serverstransport.insecureskipverify"
    environment:
      {%- for acme_resolver in backbone__acme_resolvers +%}
      {%- for acme_env_name, acme_env_value in acme_resolver.env.items() +%}
      - "{{ acme_env_name }}={{ acme_env_value }}"
      {%- endfor +%}
      {%- endfor +%}
      - LEGO_DISABLE_CNAME_SUPPORT=true # Necessary because team_domain has wildcard as a cname of apex
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 3478:3478/udp # unifi STUN
      - 10001:10001/udp # unifi AP discovery
      - 8080:8081 # unifi device communication /!\ Internally (in Traefik), uses 8081 because 8080 is taken by API => but unifi then receives it again in 8080, so should be transprent /!\
      # TODO: fix DLNA (should be exposed as physical device)
      # - 1900:1900/udp # unifi discovery on L2 network
      - 25565:25565 # Minecraft
      - 7359:7359/udp # Jellyfin client discovery
      # TODO: fix DLNA (should be exposed as physical device)
      # - 1900:1900/udp # DLNA (for Jellyfin)
      - 22000:22000/tcp # syncthing (TCP)
      - 22000:22000/udp # syncthing (UDP)
      - 21027:21027/udp # syncthing discovery
      - 10578:10578/udp # Skyrim Together Reborn server
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # certificates storage
      - "{{ docker_mounts_directory }}/traefik:/certs"
    mem_limit: 128m
    labels:
      # allow access to traefik UI
      - traefik.enable=true
      - traefik.http.routers.traefik.entryPoints=websecure
      - traefik.http.routers.traefik.rule=Host(`routing.{{ main_domain }}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=authelia@docker,traefik-compress

      # Common middlewares definitions
      - traefik.http.middlewares.lan-whitelist.ipwhitelist.sourcerange={{ internal_networks_cidr | join(",") }}
      - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth
      - traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name
      - traefik.http.middlewares.traefik-compress.compress=true

  lldap:
    image: lldap/lldap:v0.6.3@sha256:2a8454b668c1aba7157e832eab0e242e1e7eb5fb7591d7e7774ba05286511ca8
    container_name: lldap
    restart: unless-stopped
    ports:
      # For LDAP, only expose to localhost so Ansible can connect to it
      - "127.0.0.1:3890:3890"
    environment:
      TZ: {{ iana_timezone }}
      LLDAP_JWT_SECRET: {{ backbone__lldap__jwt_secret }}
      LLDAP_KEY_SEED: {{ backbone__lldap__key_seed }}
      # Output e.g. "dc=snyssen,dc=be"
      LLDAP_LDAP_BASE_DN: >-
        {{ main_domain | split(".") | map("regex_replace", "^", "dc=") | join(",") }}
      LLDAP_DATABASE_URL: >-
        postgres://{{ backbone__lldap__db_user }}:{{ backbone__lldap__db_pass }}@postgres/{{ backbone__lldap__db_user }}
    networks:
      - db
      - web
      - ldap
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      # web frontend
      - traefik.http.routers.lldap.entryPoints=websecure
      - traefik.http.routers.lldap.rule=Host(`ldap.{{ main_domain }}`)
      - traefik.http.routers.lldap.service=lldap
      - traefik.http.services.lldap.loadBalancer.server.port=17170

  authelia:
    container_name: authelia
    image: ghcr.io/authelia/authelia:4.39.20@sha256:1b363e9279e742397966333f364e0876ae02bf5c876de73e83af6d48c57ff51b
    restart: 'unless-stopped'
    networks:
      - web
      - db
      - ldap
      - monitoring
      - authelia
    depends_on:
      - authelia_redis
    environment:
      TZ: "{{ iana_timezone }}"
    {%- set main_domain_resolver = (backbone__acme_domains | selectattr("main", "equalto", main_domain) | map(attribute="resolver") | first) %}
    {%- set team_domain_resolver = (backbone__acme_domains | selectattr("main", "equalto", team_domain) | map(attribute="resolver") | first) +%}
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.services.authelia.loadBalancer.server.port=9091
      - traefik.http.routers.authelia-main.rule=Host(`auth.{{ main_domain }}`)
      - traefik.http.routers.authelia-main.entryPoints=websecure
      - traefik.http.routers.authelia-main.service=authelia
      - traefik.http.routers.authelia-main.tls.certresolver={{ main_domain_resolver }}
      - traefik.http.routers.authelia-team.rule=Host(`auth.{{ team_domain }}`)
      - traefik.http.routers.authelia-team.entryPoints=websecure
      - traefik.http.routers.authelia-team.service=authelia
      - traefik.http.routers.authelia-team.tls.certresolver={{ team_domain_resolver }}
      - traefik.http.routers.authelia-team.tls.domains[0].main={{ team_domain }}
      - traefik.http.routers.authelia-team.tls.domains[0].sans=*.{{ team_domain }}
    volumes:
      - '{{ docker_mounts_directory }}/authelia/config:/config'

  authelia_redis:
    image: redis:8.10.0@sha256:344e3945a0b431c8ff1eecd58c5573538126bd756f02fc7e218ddf1fc2546366
    container_name: authelia_redis
    restart: unless-stopped
    networks:
      - authelia
    volumes:
      - authelia_sessions:/data:rw

networks:
  web:
    external: true
  db:
    external: true
  ldap:
    external: true
  monitoring:
    external: true
  authelia:
volumes:
  authelia_sessions:
  tailscale:
