# Derived from: https://github.com/koush/scrypted/blob/main/install/docker/docker-compose.yml
services:
  scrypted:
    environment:
      SCRYPTED_NVR_VOLUME: /nvr
      # Avahi can be used for network discovery by passing in the host daemon
      # or running the daemon inside the container. Choose one or the other.
      # Uncomment next line to run avahi-daemon inside the container.
      # See volumes and security_opt section below to use the host daemon.
      # SCRYPTED_DOCKER_AVAHI: "true"

    image: ghcr.io/koush/scrypted:v0.146.0-noble-full@sha256:7f04a070a0a6382802d66a8fe16ce18c4385c7843738a2846a93063e192a37e6

    volumes:
      # Scrypted NVR Storage (Part 3 of 3)

      # Modify to add the additional volume for Scrypted NVR.
      # The following example would mount the /mnt/bulk/scrypted/nvr path on the host
      # to the /nvr path inside the docker container.
      - /mnt/bulk/scrypted/nvr:/nvr

      # Uncomment the following lines to use Avahi daemon from the host.
      # Ensure Avahi is running on the host machine:
      # It can be installed with: sudo apt-get install avahi-daemon
      # This is not compatible with running avahi inside the container (see above).
      # Also, uncomment the lines under security_opt
      # - /var/run/dbus:/var/run/dbus
      # - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

      # Default volume for the Scrypted database. Typically should not be changed.
      # The volume will be placed relative to this docker-compose.yml.
      - scrypted:/server/volume
      # Uncomment the following lines to use Avahi daemon from the host
      # Without this, AppArmor will block the container's attempt to talk to Avahi via dbus
      # security_opt:
      #     - apparmor:unconfined
    devices:
      # uncomment the common systems devices to pass
      # them through to docker.

      # all usb devices, such as coral tpu
      # "/dev/bus/usb:/dev/bus/usb",

      # hardware accelerated video decoding, opencl, etc.
      - "/dev/dri:/dev/dri"
      # AMD GPU
      # "/dev/kfd:/dev/kfd",

      # uncomment below as necessary.
      # zwave usb serial device

      # "/dev/ttyACM0:/dev/ttyACM0",

      # coral PCI devices
      # "/dev/apex_0:/dev/apex_0",
      # "/dev/apex_1:/dev/apex_1",

    container_name: scrypted
    restart: unless-stopped
    network_mode: host

    # logging is noisy and will unnecessarily wear on flash storage.
    # scrypted has per device in memory logging that is preferred.
    # enable the log file if enhanced debugging is necessary.
    logging:
      driver: "none"
      # driver: "json-file"
      # options:
      #     max-size: "10m"
      #     max-file: "10"

volumes:
  scrypted:
