services:
  backrest:
    image: garethgeorge/backrest:v1.11.2@sha256:6ecf25925dafcb6b37ab871d23c1d424a6f5008191a631c0b520641ec22a3f84
    container_name: backrest
    volumes:
      - "{{ docker_mounts_directory }}/backrest/data:/data"
      - "{{ docker_mounts_directory }}/backrest/config:/config"
      - "{{ docker_mounts_directory }}/backrest/cache:/cache"
      - "{{ docker_mounts_directory }}/backrest/tmp:/tmp"
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ={{ iana_timezone }}
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.backrest.entryPoints=websecure
      - traefik.http.routers.backrest.rule=Host(`backrest.{{ main_domain }}`)
      - traefik.http.routers.backrest.service=backrest
      - traefik.http.services.backrest.loadBalancer.server.port=9898
      - traefik.http.routers.backrest.middlewares=authelia@docker

networks:
  web:
    external: true
