services:
  backrest:
    image: garethgeorge/backrest:v1.11.0@sha256:c79b87d7da28d9a0f6ce74de96b0a4c771590b86e5066f22535d073513f31f54
    container_name: backrest
    volumes:
      - "{{ docker_mounts_directory }}/backrest/data:/data"
      - "{{ docker_mounts_directory }}/backrest/config:/config"
      - "{{ docker_mounts_directory }}/backrest/cache:/cache"
      - "{{ docker_mounts_directory }}/backrest/tmp:/tmp"
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ={{ iana_timezone }}
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.backrest.entryPoints=websecure
      - traefik.http.routers.backrest.rule=Host(`backrest.{{ main_domain }}`)
      - traefik.http.routers.backrest.service=backrest
      - traefik.http.services.backrest.loadBalancer.server.port=9898
      - traefik.http.routers.backrest.middlewares=authelia@docker

networks:
  web:
    external: true
