services:
  backrest:
    image: garethgeorge/backrest:v1.11.1@sha256:aeb0e208365981a645e94ef38e44ef5a98c6d2c8049787254db0480a4a7bc84f
    container_name: backrest
    volumes:
      - "{{ docker_mounts_directory }}/backrest/data:/data"
      - "{{ docker_mounts_directory }}/backrest/config:/config"
      - "{{ docker_mounts_directory }}/backrest/cache:/cache"
      - "{{ docker_mounts_directory }}/backrest/tmp:/tmp"
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ={{ iana_timezone }}
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.backrest.entryPoints=websecure
      - traefik.http.routers.backrest.rule=Host(`backrest.{{ main_domain }}`)
      - traefik.http.routers.backrest.service=backrest
      - traefik.http.services.backrest.loadBalancer.server.port=9898
      - traefik.http.routers.backrest.middlewares=authelia@docker

networks:
  web:
    external: true
