services:
  s-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:2.5.0@sha256:8ba3c5698d9518a4e37b5c88127cc3c0d0190feb20dee6769fc1f36d13ff6339
    container_name: s-pdf
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.s-pdf.entryPoints=websecure
      - traefik.http.routers.s-pdf.rule=Host(`pdf.{{ main_domain }}`)
      - traefik.http.services.s-pdf.loadBalancer.server.port=8080
      - traefik.http.routers.s-pdf.middlewares=authelia@docker
    volumes:
      - "{{ docker_mounts_directory }}/s-pdf/ocr:/usr/share/tesseract-ocr/5/tessdata" #Required for extra OCR languages
      - "{{ docker_mounts_directory }}/s-pdf/config:/configs"
    mem_limit: 512m
networks:
  web:
    external: true
