services:
  s-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:2.5.2@sha256:74c9ad9e280087f0652bfc98c9b5524b03ea5c138050406d2e3936f9cd60906f
    container_name: s-pdf
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.s-pdf.entryPoints=websecure
      - traefik.http.routers.s-pdf.rule=Host(`pdf.{{ main_domain }}`)
      - traefik.http.services.s-pdf.loadBalancer.server.port=8080
      - traefik.http.routers.s-pdf.middlewares=authelia@docker
    volumes:
      - "{{ docker_mounts_directory }}/s-pdf/ocr:/usr/share/tesseract-ocr/5/tessdata" #Required for extra OCR languages
      - "{{ docker_mounts_directory }}/s-pdf/config:/configs"
    mem_limit: 512m
networks:
  web:
    external: true
