services:
  s-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:2.10.0@sha256:4d9abedcd57a9aa4d36ffb8fc9a4801aea2d295bf6ad349e23dd4b45661a5e42
    container_name: s-pdf
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.s-pdf.entryPoints=websecure
      - traefik.http.routers.s-pdf.rule=Host(`pdf.{{ main_domain }}`)
      - traefik.http.services.s-pdf.loadBalancer.server.port=8080
      - traefik.http.routers.s-pdf.middlewares=authelia@docker
    volumes:
      - "{{ docker_mounts_directory }}/s-pdf/ocr:/usr/share/tesseract-ocr/5/tessdata" #Required for extra OCR languages
      - "{{ docker_mounts_directory }}/s-pdf/config:/configs"
networks:
  web:
    external: true
