name: "snyssen/whitelist-attic"
description: "Ignore GET calls on Attic's binary cache service"
whitelist:
  reason: "Attic's binary cache service expects lots of GET calls on random-looking URLs, that can result in both 200 or 404 depending on cache hit or miss."
  expression:
    - evt.Meta.http_verb 'GET' && evt.Meta.traefik_router_name == 'attic@docker'
