services:
  adguard:
    image: adguard/adguardhome:v0.107.72@sha256:4956b35b590286e5872fb4336d84a7862a2030c6efb4ca16442580c37d7ba32d
    container_name: adguard
    restart: unless-stopped
    volumes:
      - "{{ data_directory }}/adguard/work:/opt/adguardhome/work"
      - "{{ data_directory }}/adguard/conf:/opt/adguardhome/conf"
    network_mode: host
