name: Check nix flake
# This job is mainly in place so renovate can do branch automerge, as it needs a successful check.
# It then doubles as a sanity check on the flake quality
on:
  # pull_request:
  push:
    # branches:
    #   - main

jobs:
  build:
    name: Check nix flake
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@de924abd783455e8429c858962b9e43062d19da1 # main
