# This job is mainly in place so renovate can do branch automerge, as it needs a successful check.
# It then doubles as a sanity check on the flake quality
on:
  # pull_request:
  push:
    # branches:
    #   - main

jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
